### Cargar librerías

In [1]:
import numpy as np
import pandas as pd
import pyaging as pya

### Leer los datos

In [20]:
df = pd.read_csv("/home/mvaquerizo/AltumAge/data/betas_pat_sinNA.csv", index_col=0)

In [21]:
df.shape

(150, 928710)

In [22]:
df.head()

,cg25324105,cg25383568,cg25455143,cg25459778,cg25487775,cg25595446,cg25623721,cg25625370,cg25898577,cg25908985,...,cg24693072,cg21854332,cg03402369,cg16541998,cg01361899,cg18801637,cg00452270,cg13726456,cg23977670,cg01530482
PAT_1,0.034529,0.861324,0.023038,0.012294,0.442304,0.022768,0.020860,0.891113,0.176607,0.022420,...,0.800538,0.148603,0.202523,0.321204,0.088425,0.855343,0.810977,0.424717,0.585528,0.556980
PAT_9,0.035535,0.850712,0.026443,0.031078,0.469916,0.029783,0.028923,0.891913,0.219443,0.026591,...,0.805293,0.175169,0.180092,0.244115,0.098802,0.859648,0.793003,0.406356,0.593795,0.581597
PAT_25,0.042257,0.851139,0.015637,0.027566,0.414056,0.030277,0.033264,0.966146,0.157647,0.014612,...,0.799689,0.126012,0.148297,0.238712,0.146524,0.879059,0.807628,0.437606,0.587977,0.613886
PAT_10,0.017188,0.885664,0.002185,0.029460,0.479989,0.023233,0.025770,0.905877,0.142182,0.022826,...,0.817058,0.135831,0.150416,0.231876,0.126736,0.890098,0.812138,0.436393,0.591633,0.553384
PAT_21,0.028501,0.886887,0.013795,0.026552,0.484114,0.017670,0.026372,0.907140,0.138450,0.014129,...,0.816276,0.114420,0.115741,0.179871,0.123678,0.884187,0.828239,0.436873,0.581720,0.596474

### Comprobar que no hay duplicados

In [23]:
df = pya.pp.epicv2_probe_aggregation(df)

|-----> 🏗️ Starting epicv2_probe_aggregation function
|-----> ⚙️ Looking for duplicated probes started
|-----------> in progress: 100.0000%
|-----------> There are no duplicated probes. Returning original data
|-----> 🎉 Done! [22.7792s]

### Generar objeto anndata

In [24]:
adata = pya.pp.df_to_adata(df, imputer_strategy='knn')

|-----> 🏗️ Starting df_to_adata function
|-----> ⚙️ Create anndata object started
|-----> ✅ Create anndata object finished [0.9910s]
|-----> ⚙️ Add metadata to anndata started
|-----------? No metadata provided. Leaving adata.obs empty
|-----> ⚠️ Add metadata to anndata finished [0.0006s]
|-----> ⚙️ Log data statistics started
|-----------> There are 150 observations
|-----------> There are 928710 features
|-----------> Total missing values: 0
|-----------> Percentage of missing values: 0.00%
|-----> ✅ Log data statistics finished [0.1422s]
|-----> ⚙️ Impute missing values started
|-----------> No missing values found. No imputation necessary
|-----> ✅ Impute missing values finished [0.1610s]
|-----> 🎉 Done! [1.2982s]

### Predecir edad biológica

In [25]:
pya.pred.predict_age(adata, ['Horvath2013', 'AltumAge', 'zhangblup', 'zhangen'])

|-----> 🏗️ Starting predict_age function
|-----> ⚙️ Set PyTorch device started
|-----------> Using device: cpu
|-----> ✅ Set PyTorch device finished [0.0014s]
|-----> 🕒 Processing clock: horvath2013
|-----------> ⚙️ Load clock started
|-----------------> Data found in pyaging_data/horvath2013.pt
|-----------> ✅ Load clock finished [0.0090s]
|-----------> ⚙️ Check features in adata started
|-----------------? 14 out of 353 features (3.97%) are missing: ['cg01873645', 'cg07595943', 'cg09885951'], etc.
|-----------------> Using reference feature values for horvath2013
|-----------> ⚠️ Check features in adata finished [0.3232s]
|-----------> ⚙️ Predict ages with model started
|-----------------> There is no preprocessing necessary
|-----------------> The postprocessing method is anti_log_linear
|-----------------> in progress: 100.0000%
|-----------> ✅ Predict ages with model finished [0.0055s]
|-----------> ⚙️ Add predicted ages and clock metadata to adata started
|-----------> ✅ Add predicted ages and clock metadata to adata finished [0.0008s]
|-----> 🕒 Processing clock: altumage
|-----------> ⚙️ Load clock started
|-----------------> Data found in pyaging_data/altumage.pt
|-----------> ✅ Load clock finished [0.0125s]
|-----------> ⚙️ Check features in adata started
|-----------------? 814 out of 20318 features (4.01%) are missing: ['cg00050312', 'cg00078194', 'cg00079563'], etc.
|-----------------> Using reference feature values for altumage
|-----------> ⚠️ Check features in adata finished [0.3401s]
|-----------> ⚙️ Predict ages with model started
|-----------------> The preprocessing method is scale
|-----------------> There is no postprocessing necessary
|-----------------> in progress: 100.0000%
|-----------> ✅ Predict ages with model finished [0.0195s]
|-----------> ⚙️ Add predicted ages and clock metadata to adata started
|-----------> ✅ Add predicted ages and clock metadata to adata finished [0.0011s]
|-----> 🕒 Processing clock: zhangblup
|-----------> ⚙️ Load clock started
|-----------------> Data found in pyaging_data/zhangblup.pt
|-----------> ✅ Load clock finished [0.1204s]
|-----------> ⚙️ Check features in adata started
|-----------------? 32670 out of 319607 features (10.22%) are missing: ['cg12480843', 'cg11073926', 'cg11945228'], etc.
|-----------------> Using reference feature values for zhangblup
|-----------> ⚠️ Check features in adata finished [0.7663s]
|-----------> ⚙️ Predict ages with model started
|-----------------> The preprocessing method is scale_row
|-----------------> There is no postprocessing necessary
|-----------------> in progress: 100.0000%
|-----------> ✅ Predict ages with model finished [0.3948s]
|-----------> ⚙️ Add predicted ages and clock metadata to adata started
|-----------> ✅ Add predicted ages and clock metadata to adata finished [0.0011s]
|-----> 🕒 Processing clock: zhangen
|-----------> ⚙️ Load clock started
|-----------------> Data found in pyaging_data/zhangen.pt
|-----------> ✅ Load clock finished [0.0017s]
|-----------> ⚙️ Check features in adata started
|-----------------? 21 out of 514 features (4.09%) are missing: ['cg13617776', 'cg20050761', 'cg11714320'], etc.
|-----------------> Using reference feature values for zhangen
|-----------> ⚠️ Check features in adata finished [0.3200s]
|-----------> ⚙️ Predict ages with model started
|-----------------> The preprocessing method is scale_row
|-----------------> There is no postprocessing necessary
|-----------------> in progress: 100.0000%
|-----------> ✅ Predict ages with model finished [0.0019s]
|-----------> ⚙️ Add predicted ages and clock metadata to adata started
|-----------> ✅ Add predicted ages and clock metadata to adata finished [0.0008s]
|-----> 🎉 Done! [13.7954s]

#### Ver los resultados

In [26]:
adata.obs

         horvath2013   altumage  zhangblup    zhangen
PAT_1      42.231518  43.579488  51.488333  28.000645
PAT_9      47.880767  46.971568  52.484789  29.926666
PAT_25     42.756878  48.359732  52.490288  40.131480
PAT_10     45.744320  45.756896  55.410091  33.074520
PAT_21     51.540670  48.811489  59.002281  36.911033
...              ...        ...        ...        ...
PAT_189    40.504331  47.274070  53.243206  31.347947
PAT_149    45.881387  49.596570  58.523053  41.597198
PAT_162    48.327891  48.909006  65.531797  47.658273
PAT_163    42.937699  45.791731  50.091848  29.962253
PAT_150    44.803489  47.571209  57.123527  35.261162

[150 rows x 4 columns]

### Guardar los resultados

In [27]:
adata.obs.to_csv(path_or_buf='bioage_pat_pyaging.csv',index=True)